---
- name: Download Rider Tarball
  become: no
  get_url:
      url: "https://download.jetbrains.com/resharper/JetBrains.Rider-{{rider_version}}.tar.gz"
      dest: "{{ansible_user_dir}}/{{base_download_directory}}/rider-{{rider_version}}.tar.gz"
      mode: 0444
  when: rider_install

- name: Uncompress Rider Tarball
  become: no
  unarchive:
      src: "{{ansible_user_dir}}/{{base_download_directory}}/rider-{{rider_version}}.tar.gz"
      dest: "{{ansible_user_dir}}/{{base_software_directory}}"
      copy: no
      owner: "{{ansible_user_uid}}"
      group: "{{ansible_user_gid}}"
      mode: 0555
      creates: "{{ansible_user_dir}}/{{base_software_directory}}/JetBrains Rider-{{rider_version}}/build.txt"
  when: rider_install

- name: Create Softlink To Rider
  become: no
  file:
      src: "{{ansible_user_dir}}/{{base_software_directory}}/JetBrains Rider-{{rider_version}}"
      dest: "{{ansible_user_dir}}/{{base_software_directory}}/rider"
      owner: "{{ansible_user_uid}}"
      group: "{{ansible_user_gid}}"
      state: link
  when: rider_install

- name: Create Desktop Icon For Rider
  become: no
  template:
      src: "templates/rider.desktop.j2"
      dest: "{{ansible_user_dir}}/Desktop/rider.desktop"
      owner: "{{ansible_user_uid}}"
      group: "{{ansible_user_gid}}"
      mode: 0755
  when: rider_install

- name: Set Global Environment To Have GoLand Use Shared JDK
  become: yes
  template:
      src: "templates/rider-environment.sh.j2"
      dest: "/etc/profile.d/rider-environment.sh"
      owner: "{{ansible_user_uid}}"
      group: "{{ansible_user_gid}}"
      mode: 0555
  when: rider_install

- name: Remove Rider's Embedded JDK
  become: no
  file:
      path: "{{ansible_user_dir}}/{{base_software_directory}}/rider/jre"
      state: absent
  when: rider_install
